// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Model.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20190910075408_setattribute")]
    partial class setattribute
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InterfaceDB.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasMaxLength(25);

                    b.Property<float>("AvgReview");

                    b.Property<int>("CountCustomers");

                    b.Property<string>("Cover")
                        .HasMaxLength(10);

                    b.Property<int>("Data");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("Dimensions")
                        .HasMaxLength(10);

                    b.Property<long>("ISBN_10");

                    b.Property<long>("ISBN_13");

                    b.Property<string>("Language")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("Publisher")
                        .HasMaxLength(20);

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
